### ISSUE TITLE
Follow TCD Night Mode, with Show Clock and Screen Saver - Enhancement

### ISSUE THREAD

**Issue by TechieNetGuy** [realA10001986/SID#1]
Would it be possible for the following?

If "follow TCD night-mode" and "show clock when screen saver is active", then show the clock with dimmer light level - much like the display on the TCD can be dimmed?

Full/Normal Brightness with "show clock when Screen Saver is active" while the TCD is not in night-mode, or the option to follow the TCD night-mode is not selected.

**Comment by TechieNetGuy** [comment]
It could be a "sub" option under "Show clock when Screen Saver is active" maybe?!  

(X) - Show clock when Screen Saver is active
- (X) - Dim clock when TCD in night-mode

**Comment by realA10001986** [comment]
Good idea. I don't think the option is required; night-mode per se should be .. night-mode. I'll get to it when I am done with my ongoing TCD changes.

**Comment by TechieNetGuy** [comment]
Works!
