### ISSUE TITLE
Brightness Control - without remote (Config Portal or TCD Keypad Commands)

### ISSUE THREAD

**Issue by TechieNetGuy** [realA10001986/SID#2]
Would be nice to be able to adjust the Brightness without the use of the remote, either via the Config Portal or TCD Commands over BTTFN - or both.

Additionally maybe be able to adjust each color separately for different levels (much like the TCD), as I find the yellow and red to be more intense than the green.

**Comment by realA10001986** [comment]
Can't control the brightness per color, the LEDs are connected to the same controller. Only one brightness per controller.

I'll think about the remote-less way, but I am busy with the TCD for now.

**Comment by TechieNetGuy** [comment]
Works!
