### ISSUE TITLE
intermittent boot issue

### ISSUE THREAD

**Issue by doc1011** [realA10001986/SID#3]
Hi 

I've noticed a few times that when powering on the SID, it seems to loop the boot sequence, where all LEDs light up before falling down and starting the pattern - it will simply repeat all LEDs lighting up over and over. Whenever this happens a power cycle solves the issue. It's powered via the 5v on the ESP32. 

Thanks!

Love the games on it, by the way!

**Comment by realA10001986** [comment]
Hi!

Your description points a power supply issue. The boot sequence lights up all LEDs, which might overload your power supply. 

BTW, the props are meant to be powered via their 5V or 12-20V terminals; the USB is more for testing or programming. I don't know the exact power rating, but a 5V/2A supply is probably enough (more amps wouldn't hurt though)

**Comment by doc1011** [comment]
Great, thank you - I'll try a proper PSU. 

Cheers!
