### ISSUE TITLE
Losing settings

### ISSUE THREAD

**Issue by doc1011** [realA10001986/SID#4]
Hi

Over the past few days I've noticed that the SID is losing all its settings when powered off/on - it is intermittent and doesn't seem to happen every time. The PSU is 12V/5A, and the SID has had daily use. Anything to check? 

Cheers

**Comment by realA10001986** [comment]
"All" settings: How do you recognize this? What does the SID do what it shouldn't do? Are we talking the settings set up in the Config Portal?

Do you have an SD card in the slot?

**Comment by doc1011** [comment]
Hi - yes in the config portal. The only section where I'm not using default settings is the BTTFN network section (pic below). It forgets the TCD IP and won't follow the fake power on, nighttime etc. 

It does have an SD card in the slot. I can't remember if I had previously set the SID to save secondary settings on the SD card before the issues started, although I probably did.

![Screenshot 2024-08-29 at 11 53 53](https://github.com/user-attachments/assets/378307a0-8876-4744-9fe8-dbd951648422)

**Comment by realA10001986** [comment]
Mine never did that. What probably happens is that it encounters a bad config file and re-writes defaults. Sounds a bit like a hardware problem (bad ESP32 board, with bad flash memory) at first glance. 

Remarkingly, you had the same problem with the flux capacitor a while back, which I neither could reproduce, .. what's the status there?

**Comment by doc1011** [comment]
Yes good point - I ended up getting a replacement ESP32 board in the end for the flux and it's been fine since. 

I was hoping I was doing something wrong and it would be an easier fix and save me some shipping costs for a new part;) Maybe I should buy a few as backups.

**Comment by realA10001986** [comment]
What you can do in the meantime is place a file on the SD card named "SID_FLASH_RO" (without appendix). This will force the SID to save all its settings on the SD, and avoid the flash.
